---
class: 4
flags: 0x0000
unid: OFED22BDE795F79B77-ON0030E79E852574AD
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: WEB-INF/faces-config.xml
    signed: true
  - name: $Flags
    type: text
    data: ~Cg4
  - name: $FlagsExt
    type: text
    data: w
    signed: true
  - name: $TITLE
    type: text
    data: WEB-INF/faces-config.xml
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []