---
class: 4
flags: 0x0000
unid: OF951EB233716C0558-ON00539D2985257451
items:
  - name: $FileNames
    type: text
    data: ".classpath"
    signed: true
  - name: $Flags
    type: text
    data: ~Cg
  - name: $LANGUAGE
    type: text
    data: en
    signed: true
  - name: $TITLE
    type: text
    data: ".classpath"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []