---
ACL:
  opaque: |
    Q0ECACAIBgAAAAAABQDWBhAAJgdGBwECAAAoAAQAAAAEBCgAogYUADA3LzI1LzIwMjIgMTA6NDk6MjAg
    QU0gTWFpdHJleWVlIFBhdHVrYWxlL0luZGlhL1BOUEhDTCBkZWxldGVkIFtbLURlZmF1bHQtXV0AMDcv
    MjUvMjAyMiAxMDo0OToyMCBBTSBNYWl0cmV5ZWUgUGF0dWthbGUvSW5kaWEvUE5QSENMIGFkZGVkIExv
    Y2FsRG9tYWluU2VydmVycwAwNy8yNS8yMDIyIDEwOjQ5OjIwIEFNIE1haXRyZXllZSBQYXR1a2FsZS9J
    bmRpYS9QTlBIQ0wgZGVsZXRlZCBbW0xvY2FsRG9tYWluU2VydmVyc11dADA3LzI1LzIwMjIgMTA6NDk6
    MjAgQU0gTWFpdHJleWVlIFBhdHVrYWxlL0luZGlhL1BOUEhDTCBkZWxldGVkIExvY2FsRG9tYWluQWRt
    aW5zADA3LzI1LzIwMjIgMTA6NDk6MjAgQU0gTWFpdHJleWVlIFBhdHVrYWxlL0luZGlhL1BOUEhDTCBk
    ZWxldGVkIE1haXRyZXllZSBQYXR1a2FsZS9JbmRpYS9QTlBIQ0wAMDcvMjUvMjAyMiAxMDo0OToyMCBB
    TSBNYWl0cmV5ZWUgUGF0dWthbGUvSW5kaWEvUE5QSENMIGRlbGV0ZWQgU2NvdHQgTydLZWVmZS9VU0Ev
    UE5QSENMADA3LzI1LzIwMjIgMTA6NDk6MjAgQU0gTWFpdHJleWVlIFBhdHVrYWxlL0luZGlhL1BOUEhD
    TCBkZWxldGVkIFRyYW5zbGF0YWJpbGl0eVRlbXBsYXRlRGV2ZWxvcGVycwAwNy8yNS8yMDIyIDEwOjQ5
    OjIwIEFNIE1haXRyZXllZSBQYXR1a2FsZS9JbmRpYS9QTlBIQ0wgZGVsZXRlZCBBbWl0IEggQm9yYS9J
    bmRpYS9QTlBIQ0wAMDcvMjUvMjAyMiAxMDo0OToyMCBBTSBNYWl0cmV5ZWUgUGF0dWthbGUvSW5kaWEv
    UE5QSENMIGRlbGV0ZWQgTWFzdGVya2V5L1NlcnZlci9UZW1wbGF0ZXMAMDcvMjUvMjAyMiAxMDo0OToy
    MCBBTSBNYWl0cmV5ZWUgUGF0dWthbGUvSW5kaWEvUE5QSENMIGRlbGV0ZWQgTWFzdGVybG9jay9TZXJ2
    ZXIvVGVtcGxhdGVzADA3LzI1LzIwMjIgMTA6NDk6MjAgQU0gTWFpdHJleWVlIFBhdHVrYWxlL0luZGlh
    L1BOUEhDTCBkZWxldGVkIEFuZHJlIEd1aXJhcmQvVVNBL1BOUEhDTAAwNy8yNS8yMDIyIDEwOjQ5OjIw
    IEFNIE1haXRyZXllZSBQYXR1a2FsZS9JbmRpYS9QTlBIQ0wgZGVsZXRlZCBBbm9ueW1vdXMAMDcvMjUv
    MjAyMiAxMDo0OToyMCBBTSBNYWl0cmV5ZWUgUGF0dWthbGUvSW5kaWEvUE5QSENMIHVwZGF0ZWQgTWFz
    dGVybG9jay9TZXJ2ZXIvVGVtcGxhdGVzADExLzEwLzIwMjEgMDk6MjQ6NDIgQU0gQW5kcmUgR3VpcmFy
    ZC9VU0EvUE5QSENMIHVwZGF0ZWQgU2NvdHQgTydLZWVmZS9VU0EvUE5QSENMADExLzEwLzIwMjEgMDk6
    MjQ6NDIgQU0gQW5kcmUgR3VpcmFyZC9VU0EvUE5QSENMIGFkZGVkIFNjb3R0IE8nS2VlZmUvVVNBL1BO
    UEhDTAAwNy8xOS8yMDIxIDAyOjAxOjIyIFBNIE1haXRyZXllZSBQYXR1a2FsZS9JbmRpYS9QTlBIQ0wg
    dXBkYXRlZCBBbWl0IEggQm9yYS9JbmRpYS9QTlBIQ0wAMDcvMTkvMjAyMSAwMjowMToxNyBQTSBNYWl0
    cmV5ZWUgUGF0dWthbGUvSW5kaWEvUE5QSENMIGFkZGVkIEFtaXQgSCBCb3JhL0luZGlhL1BOUEhDTAAy
    MDE5LzA0LzI5IDA1OjQ0OjMzIFBNIEFuZHJlIEd1aXJhcmQvVVNBL1BOUEhDTCBkZWxldGVkIFFpYW4g
    TGlhbmcvQ2hpbmEvSUJNADIwMTkvMDQvMjkgMDU6NDQ6MjkgUE0gQW5kcmUgR3VpcmFyZC9VU0EvUE5Q
    SENMIGRlbGV0ZWQgRGViYmllIEJyYW5jby9XZXN0Zm9yZC9JQk0AMjAxOS8wNC8yOSAwNTo0NDoyMiBQ
    TSBBbmRyZSBHdWlyYXJkL1VTQS9QTlBIQ0wgYWRkZWQgQW5kcmUgR3VpcmFyZC9VU0EvUE5QSENMAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZAcAAAAAAAAAAAAAAAAAAAAAjgcAAPgH2AcAAAAA
    AAAAAEVBAgAAAAAAAAAAAAAAHQIJAC1EZWZhdWx0LQAAAEVBAAAAAAAAAAAAAAAARwYUAFtPdGhlckRv
    bWFpblNlcnZlcnNdAACuB0VBAAAAAAAAAAAAAAAABQYLAFstRGVmYXVsdC1dAAAARUEGAAAAAAAAAAAA
    AADaBxQAW0xvY2FsRG9tYWluU2VydmVyc10AAAAARUEAAAAAAAAAAAAAAAAFBgsAW0Fub255bW91c10A
    AABFQQYAAAAAAAAAAAAAAJgHEgBMb2NhbERvbWFpblNlcnZlcnMAbw==
DBOptions: 0x00000800
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0